print('                 MIS 303: Business Application Programming')
name = 'Zachary Warshaw'
print()
print('Assignment 1', "\n"'Name:', name)
print()
print('This app serves as a checkout system for the “Anaconda’s Pit” Motel')
print()
customer = input("Enter Customer Name:")
room = input("Enter Room Number:")
rental_nights = input('Number of Nights Staying:')
rental_nights = int(rental_nights)
cost_per_room = 23.59
total_cost = (cost_per_room*rental_nights)
print()
print('Customer Name:', customer)
print('Room Number:', room)
print('Number of Nights:', rental_nights)
print('Room Cost:', cost_per_room)
print('Total Cost:', total_cost)
