print('This app is used to calculate the breakeven point for your business')
print()
Business_name = input('Enter business\'s name:')
Name = input('Enter your name:')
role = input('What is your role?:')
even = input('What product is this break even analysis being done for?:')
print()
sell_price = float(input('Enter selling price for one unit of product:'))
one_unit = float(input('Enter the cost for developing one unit of product:'))
fixed_cost = float(input('Enter the fixed cost in the development of this product:'))
print()
print('Business:', Business_name, '\t\t\t Name:', Name, '\t\t\t Role:', role)
profit = int(fixed_cost/(sell_price-one_unit))
print('You will need to sell', profit, 'Units of', even, 'to make break even.')
